name = "buildnblocks"

# ğŸ’¡ 1. Point 'main' to the new Worker file you created.
main = "src/worker.js" 
compatibility_date = "2025-10-02"

# ğŸ› ï¸ 2. Point 'bucket' to your static assets folder.
[site]
bucket = "./public" 
